on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
      
    #- name: API
     # run: ' curl -s -u admin:carboidrato2911 https://sonarqube.com/api/sqp_fe878e7ec800b45961a01cb452423cd5200e15f8/search'
      
    - name: SonarCloud Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
          args: -X
            -Dsonar.host.url=https://172.17.0.2:9000
            -Dsonar.projectKey=local
            -Dsonar.sources=.
           
